### ISSUE TITLE
Display of Luxembourg maps (ACT)

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#13]
(moved from the closed issue #1) 
In the process of creating a new site, I clicked on "Save" at the bottom of "Site details". It induced a switch in the maps from ACT (LU maps) to Google maps. ACT maps are not anymore visible, in the "Your route" tab neither, and even by re-editing the site.
- If I create a new site, ACT maps are ok until I click "Save"
- It occurs in both "My sites" and "Country sites"

**Comment by xaviermestdagh** [comment]
@Gary-van-Breda this bug still occurs

**Comment by Gary-van-Breda** [comment]
Sorry @xaviermestdagh , I can't reproduce this. Could you let me know exactly how you get the problem - what steps do you follow? e.g. How go you enter the location? What values are in the fields?
Many Thanks.

**Comment by Gary-van-Breda** [comment]
@xaviermestdagh OK, don't worry, I've logged in as you, and can see the problem

**Comment by Gary-van-Breda** [comment]
Problem was caused by an incorrected named country field when the user does not have permission to modify the country on an existing site.
 
@BirenRathod : could I have the develop branch versions of the following files deployed?

https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/ebms_sectioned_transects_edit_transect.php
https://github.com/Indicia-Team/client_helpers/blob/develop/prebuilt_forms/sectioned_transects_edit_transect.php

Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda  This has been uploaded on to the ebms live site.

**Comment by Gary-van-Breda** [comment]
@xaviermestdagh : can you try again - it now looks OK to me.

**Comment by xaviermestdagh** [comment]
Yes thanks it's great!
