### ISSUE TITLE
Sections disappear when reedit a site

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#17]
#12 perhaps not completely fixed : I managed to draw sections, edit section details and save, but when reediting the site sections disapeared.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can we switch on the log_browser module on warehouse2, and set the log threshold (in application/config/config.php) to 4.
The log threshold increase would be temporary, until EBMS is sorted.

**Comment by BirenRathod** [comment]
I enabled the module and set the threshold to 4.

**Comment by Gary-van-Breda** [comment]
I have switched off the mandatory flag on the new Linear Feature section attribute. The route was being rejected on the server because there was no attached attribute. I can now save the routes; but - issues: 

- There seems to be a cross domian proxy problem when using "butterfly-monitoring.net" rather than "www.butterfly-monitoring.net"
- The code needs to be changed so a client side only mandatory validation can be added to the Linear Feature section attribute.

**Comment by DavidRoy** [comment]
@BirenRathod please investigate:
There seems to be a cross domian proxy problem when using "butterfly-monitoring.net" rather than "www.butterfly-monitoring.net"

**Comment by BirenRathod** [comment]
I don't see any problem while accessing the site. Is there any specific page I need to look into?

**Comment by BirenRathod** [comment]
by clearing the cookies may help.......

**Comment by Gary-van-Breda** [comment]
The place where I noticed it was entering a route on a site, where an ajax call is failing because its trying to call a www url from a non-www page.
This can also be seen if you try to use the masquerade autocomplete from butterfly-monitoring.net - it works OK from www.butterfly-monitoring.net.

**Comment by Gary-van-Breda** [comment]
@xaviermestdagh : could you check the original issue again?  The code deployment done in #13 earlier today should also have fixed this.

**Comment by xaviermestdagh** [comment]
Yes indeed the original issue is fixed. If on your side the bug related to the www vs non-www is fixed as well this issue can be closed...
