### ISSUE TITLE
Add complexe of species in the liste of species

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#32]
Would it be possible to add those complexe of species?
- Pieris sp.
- Colias hyale/alfacariensis
- Pyrgus armoricanus/serratulae
- Leptidea sinapis/juvernica
- Apatura ilia/iris
- Thymelicus sp.
That's for Luxembourg, perhaps there are some other complexes used somewhere else in Europe...

**Comment by DavidRoy** [comment]
Agreed.  This is a good point and I'll ask others in eBMS about complexes that could be added

**Comment by xaviermestdagh** [comment]
Would it be possible to already add those complexes in order to allow our encoding?

**Comment by DavidRoy** [comment]
That should be done.  Please confirm

**Comment by xaviermestdagh** [comment]
Sorry I cannot see any of them. In addition, _Leptidea juvernica_ seems missing

**Comment by DavidRoy** [comment]
@Gary-van-Breda I've added the extra taxa into the species list on the warehouse.  Can you advise why they don't automatically appear on the input forms?  Have I not setup them up correctly?

**Comment by Gary-van-Breda** [comment]
No they were set up correctly. It looks like the scheduled tasks (which should run every 15 minustes) have not run on warehouse2 since May 30th. @BirenRathod do you know why?
Part of the scheduled tasks is updating the species cache with changes to the database. This had not been done. The species cache is what is used by the input forms.
As a workaround, I have run the scheduled tasks manually, so the new complexes etc are now visible on the forms.

**Comment by DavidRoy** [comment]
@xaviermestdagh please close the issue if resolved
@BirenRathod please add alerting to warehouse2 so we can check that the scheduled tasks runs

**Comment by xaviermestdagh** [comment]
Ok for me, complexes are included in the list of species. I close the issue. Thanks.

**Comment by BirenRathod** [comment]
Scheduled tasks was created under my username. It starts using my authentication. After 30th, I changed my password on my machine which caused of starting the scheduled tasks. It has been modified now.
