### ISSUE TITLE
Section mapping updates

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#36]
Would it be possible to:
- add Lat/Long (or X/Y for Lux) coordinates of the cursor on the map like you did here for instance [](http://biomonitor.mnhn.lu/node/599)
- change de line type used for displaying sections: the broken line is too "brokened" so that start and end of sections are not clear and confusing for users.

**Comment by Gary-van-Breda** [comment]
Do you want the mouse control on both the Site tab map, and the map on the routes tab, or just one of them?

**Comment by xaviermestdagh** [comment]
The coordinates pointed by the cursor are interesting for the drawing of sections, so no need them on the Site details tab (only the Route tab).

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you deploy the following files to the EBMS Live Site? Thanks
[ebms_sectioned_transects_edit_transect.zip](https://github.com/BiologicalRecordsCentre/eBMS/files/1397939/ebms_sectioned_transects_edit_transect.zip)

They should be put in the existing iform/client_helpers/prebuilt_forms directory, with the files in the css and js subdirectories in the zip going into the appropriate subdirectories as well.

Includes the fix for issue #39 as well.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I have copied this file in to this folder.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : Thanks.
@xaviermestdagh : Fixes for both these bullet points now deployed. Can you check you are happy with them? If so, then this issue can be closed.

**Comment by xaviermestdagh** [comment]
Great. thanks!
