### ISSUE TITLE
Country level report (occurences and samples)

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/eBMS#41]
I did not find the way to get an occurence report and a sample report including all observations of all Luxembourg sites. The combination "All recorders" and "All sites" only allows summary and estimate tables.

**Comment by Gary-van-Breda** [comment]
This is due to data restriction issues: the full data set can only the downloaded by the superuser.
In order to see these extra downloads, you must either choose Filter by your own data (data entered by you), your country data (data on sites allocated to you at a country level), or be a superuser.
Part of the problem is that you do not have these locations assigned to you at a country level, only as a normal user. I have altered the configuration of the transect allocation form to allow the country managers to assign at a country level as well as at a normal user.
I would suggest you assign yourself to the Luxembourg sites at a country manager level using the Transect allocation form. You can leave yourself assigned at a normal level user as well if you so wish.
You can the choose to Filter by "Country Data", which will then include all the data for the sites allocated to you at the country level, and will include the download links.

**Comment by xaviermestdagh** [comment]
That's great, thanks!
